(cl:in-package rfid_msg-msg)
(cl:export '(INDUCTIONPOSITION1-VAL
          INDUCTIONPOSITION1
          INDUCTIONSIGNAL1-VAL
          INDUCTIONSIGNAL1
          INDUCTIONPOSITION2-VAL
          INDUCTIONPOSITION2
          INDUCTIONSIGNAL2-VAL
          INDUCTIONSIGNAL2
))