(cl:in-package rfid_msg-msg)
(cl:export '(ACCX-VAL
          ACCX
          ACCY-VAL
          ACCY
          ACCZ-VAL
          ACCZ
          POSRESULT-VAL
          POSRESULT
          ERROR-VAL
          ERROR
          INACCURATE-VAL
          INACCURATE
          ANALYSISERROR-VAL
          ANALYSISERROR
          TDIFFERROR-VAL
          TDIFFERROR
          SPEEDERROR-VAL
          SPEEDERROR
          SPEEDSIGNERROR-VAL
          SPEEDSIGNERROR
          SPEEDACCELERATIONERROR-VAL
          SPEEDACCELERATIONERROR
          POSOUTOFBOUNDSERROR-VAL
          POSOUTOFBOUNDSERROR
          NORESULTERROR-VAL
          NORESULTERROR
          POSITIONRESULTFAULT-VAL
          POSITIONRESULTFAULT
))