// Generated by gencpp from file rfid_msg/PDO3.msg
// DO NOT EDIT!


#ifndef RFID_MSG_MESSAGE_PDO3_H
#define RFID_MSG_MESSAGE_PDO3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rfid_msg
{
template <class ContainerAllocator>
struct PDO3_
{
  typedef PDO3_<ContainerAllocator> Type;

  PDO3_()
    : gyroX(0.0)
    , gyroY(0.0)
    , gyroZ(0.0)
    , rfidSignal1(0.0)
    , rfidSignal2(0.0)  {
    }
  PDO3_(const ContainerAllocator& _alloc)
    : gyroX(0.0)
    , gyroY(0.0)
    , gyroZ(0.0)
    , rfidSignal1(0.0)
    , rfidSignal2(0.0)  {
  (void)_alloc;
    }



   typedef float _gyroX_type;
  _gyroX_type gyroX;

   typedef float _gyroY_type;
  _gyroY_type gyroY;

   typedef float _gyroZ_type;
  _gyroZ_type gyroZ;

   typedef float _rfidSignal1_type;
  _rfidSignal1_type rfidSignal1;

   typedef float _rfidSignal2_type;
  _rfidSignal2_type rfidSignal2;





  typedef boost::shared_ptr< ::rfid_msg::PDO3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rfid_msg::PDO3_<ContainerAllocator> const> ConstPtr;

}; // struct PDO3_

typedef ::rfid_msg::PDO3_<std::allocator<void> > PDO3;

typedef boost::shared_ptr< ::rfid_msg::PDO3 > PDO3Ptr;
typedef boost::shared_ptr< ::rfid_msg::PDO3 const> PDO3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rfid_msg::PDO3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rfid_msg::PDO3_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rfid_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rfid_msg': ['/home/marco/yes_we_can/ros_layer/rosserial_ws/src/rfid_msg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rfid_msg::PDO3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rfid_msg::PDO3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfid_msg::PDO3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfid_msg::PDO3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfid_msg::PDO3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfid_msg::PDO3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rfid_msg::PDO3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ad77accb5978b7a753a2d9c57d247a9";
  }

  static const char* value(const ::rfid_msg::PDO3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ad77accb5978b7aULL;
  static const uint64_t static_value2 = 0x753a2d9c57d247a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rfid_msg::PDO3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rfid_msg/PDO3";
  }

  static const char* value(const ::rfid_msg::PDO3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rfid_msg::PDO3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 gyroX\n\
float32 gyroY\n\
float32 gyroZ\n\
float32 rfidSignal1\n\
float32 rfidSignal2\n\
";
  }

  static const char* value(const ::rfid_msg::PDO3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rfid_msg::PDO3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gyroX);
      stream.next(m.gyroY);
      stream.next(m.gyroZ);
      stream.next(m.rfidSignal1);
      stream.next(m.rfidSignal2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PDO3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rfid_msg::PDO3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rfid_msg::PDO3_<ContainerAllocator>& v)
  {
    s << indent << "gyroX: ";
    Printer<float>::stream(s, indent + "  ", v.gyroX);
    s << indent << "gyroY: ";
    Printer<float>::stream(s, indent + "  ", v.gyroY);
    s << indent << "gyroZ: ";
    Printer<float>::stream(s, indent + "  ", v.gyroZ);
    s << indent << "rfidSignal1: ";
    Printer<float>::stream(s, indent + "  ", v.rfidSignal1);
    s << indent << "rfidSignal2: ";
    Printer<float>::stream(s, indent + "  ", v.rfidSignal2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RFID_MSG_MESSAGE_PDO3_H
