# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rfid_msg/PDO2.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PDO2(genpy.Message):
  _md5sum = "e090932213462699dc59df25654c653e"
  _type = "rfid_msg/PDO2"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 inductionPosition1
float32 inductionSignal1
float32 inductionPosition2
float32 inductionSignal2
"""
  __slots__ = ['inductionPosition1','inductionSignal1','inductionPosition2','inductionSignal2']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       inductionPosition1,inductionSignal1,inductionPosition2,inductionSignal2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PDO2, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.inductionPosition1 is None:
        self.inductionPosition1 = 0.
      if self.inductionSignal1 is None:
        self.inductionSignal1 = 0.
      if self.inductionPosition2 is None:
        self.inductionPosition2 = 0.
      if self.inductionSignal2 is None:
        self.inductionSignal2 = 0.
    else:
      self.inductionPosition1 = 0.
      self.inductionSignal1 = 0.
      self.inductionPosition2 = 0.
      self.inductionSignal2 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.inductionPosition1, _x.inductionSignal1, _x.inductionPosition2, _x.inductionSignal2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.inductionPosition1, _x.inductionSignal1, _x.inductionPosition2, _x.inductionSignal2,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.inductionPosition1, _x.inductionSignal1, _x.inductionPosition2, _x.inductionSignal2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.inductionPosition1, _x.inductionSignal1, _x.inductionPosition2, _x.inductionSignal2,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
