(cl:in-package rfid_msg-msg)
(cl:export '(TAGINFIELD-VAL
          TAGINFIELD
          CODEOK-VAL
          CODEOK
          XYDEVIATIONDETERMINED-VAL
          XYDEVIATIONDETERMINED
          CENTERPULS-VAL
          CENTERPULS
          POSITIONERROR-VAL
          POSITIONERROR
          POSITIONESTIMATE-VAL
          POSITIONESTIMATE
          FATALERROR-VAL
          FATALERROR
          ANTENNASTARTED-VAL
          ANTENNASTARTED
          RFIDCODE-VAL
          RFIDCODE
          XDEVIATION-VAL
          XDEVIATION
          YDEVIATION-VAL
          YDEVIATION
))